### ISSUE TITLE
Set chastity bra to hide nipple piercings (AA update).

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#100]

**Comment by MinLL** [comment]
This should be done through AA slot, so that it works on NPC's.

**Comment by Coopervane** [comment]
Yup, should be as simple as adding slot 51 to the bra AA, and making sure the Bra has a higher priority

**Comment by MinLL** [comment]
Resolved in 951a917f2a9c4aaeb04de1ae5668cb23aa16bbb3.
