### ISSUE TITLE
add debtors perk

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#116]
Perk should take the first 3000 gold the user gets then disappear. Bonus points if you can put the current remaining total in the spell effect text

**Comment by MinLL** [comment]
What happens if the user is stuck in a second yoke while still paying off the gold?

**Comment by Aelie1** [comment]
Can we have it simply add 3000 to the current debt?

**Comment by MinLL** [comment]
Hmm. The more I think about this, the less I like it. Let's further discuss this on Skype later.
