### ISSUE TITLE
Re add blacksmith dialog text

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#120]
The blacksmith faction checks aren't working for dialogue (They're defaulting to the standard yoke dialogue). 

Remember, >= 0 means they're in a faction. A negative value means that they are not. The debtor quest needs to be tested after this is fixed, though it will probably work.

**Comment by Aelie1** [comment]
somehow it got overwritten.  the dialog can be found in this revision

https://github.com/DeviousDevices/DDi/blob/b0b542d4f0abbaa164ee6c3296381cb672cfb735/Devious%20Devices%20-%20Integration.esm
