### ISSUE TITLE
Armbinder +

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#123]
this is a stricter armbinder with more straps and locks.  functionally identical, it is to be used when the armbinder is inescapable.

To be completed when koffii gets around to it sometime(?)

**Comment by MinLL** [comment]
Model swap, instead of a new armbinder?

**Comment by Aelie1** [comment]
maybe.  i can see some quest armbinders using it straight up

**Comment by Versh** [comment]
Uhm... much thing could go wrong with this, we all know that the quest system in Skyrim is a bit messy...

I suggest (Only for this item) a secure to unequip it... Eventually with a check that looks if the quest associated (Papyrus util string on the armbinder) still running or not...

**Comment by TheKimy** [comment]
I don't think we're getting new art assets in the foreseeable future. Closed.
