### ISSUE TITLE
Mod wide difficulty level

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#125]
A mod wide difficulty level will affect the following:

-Materials to make keys
-Lock jamming chance
-Key break chance
-Chance for NPCs to help you out of armbinder/yoke
-Blacksmith yoke removal price
-Gag experience rate
-Minimum struggle amount
-Struggle chance
-Arousal gain

**Comment by TwilekQueen** [comment]
Do you mean a preset (that simply sets separate options in bulk) or actual one button deciding all those things?

**Comment by Aelie1** [comment]
undecided. i think we could make a whole difficulty page that has all these options on it or have just one option that decides it all at once

**Comment by MinLL** [comment]
Probably a "Difficulty" page, with a button that sets these options in bulk.

**Comment by TheKimy** [comment]
Not a fan of one setting that affects a thousand individual values. Will implement the additional ones as separate sliders instead.
