### ISSUE TITLE
Expand inflatable plugs with a few more options / effects.

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#14]
Anyone having any Ideas/text for events/effects?

**Comment by Versh** [comment]
I agree with Coopervane... but a valve is a bit too tecnological (Yeah yeah.. 'The looOOOoore' :P and we still talking to a thing that tecnically is rubber)
The actual is a good compromise to me... considering also that a slave isn't keep for too long on 'high pressure', the dragonborn instead could stay 2 month like that and 'how cares?'
Also consider that the Slave could reach the valve itself, the valve thing will work only if theres a Master to check the Slave(also the Master couldn't know how inflated is the plug... the slave yes)

Anyway I have 2 suggestion:
1)Why simply we do not consider this item in "stages"?
Level 0 -> Standard plug
Level 1 -> Inflated Small "malus"
Level 2 -> = medium
Level 3 -> = High
Level 4 -> = Huge
Level 5 -> = Deflating (malus of the level but get a "bonus relief")

2)In case that the valve system is accepted: Not properly an event but a dialog where the player (with the hands blocked) could ask in different way (Intimidation or Persuasion) to deflate the Plugs to someone, If success they deflate, If fail they Inflate (maybe with a check on the relationship rank, a friend will probably deflate, an enemy will do the opposite)
This will allow also some 'tactics', an enemy will Inflate the plug most of the time, but if he/she inflate the plugs over the 4 level the "secure" will deflate all the plug

It is obviously an approximation, everyone notice a huge deflation for the air release, but the trick thing could be funny in therm of gameplay...

**Comment by Teruah** [comment]
Don't know how practical it would be, but I would like to see some kind of stages as well (like Coopervane and Versh said). In addition, a possibility would be to have persistent debuffs to HP/Stamina. Think some time ago, I saw a mod that prevented your HP from reaching maximum values, but I'm certainly not sure how they went about doing it.

Think the most logical debuffs would be the Stamina/Movement scale values, although having HP drain as a periodic event would be cool. Drawing a blank for the most part beyond this.
