### ISSUE TITLE
Investigate possible problem with "collarPostureLeatherRendered".

### ISSUE THREAD

**Issue by Coopervane** [DeviousDevices/DDi#143]
Posted here:

http://www.loverslab.com/topic/21484-devious-devices-integration-02022015/?p=1079156

**Comment by Coopervane** [comment]
Yup, it's a thing.

"[03/15/2015 - 09:26:01AM] Error: Property collarPostureLeatherRendered on script zadlibs attached to zadQuest (0E00F624) cannot be bound because <NULL form> (0E047003) is not the right type"

Looks like something wasen't linked right in the Zadlibs quest stuffs.

**Comment by TheKimy** [comment]
Fixed.
