### ISSUE TITLE
Enhance modEvents system to make use of new conventions

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#147]

**Comment by TheKimy** [comment]
Anyone remembers what the "new conventions" are and why we want them? :)

**Comment by MinLL** [comment]
The new conventions are the ModEvent.Create / push / send workflow. You've already implemented the core mod events that were going to be covered under this issue. And yes, Create/push/send was, at one point, a "new" workflow. :P

**Comment by TheKimy** [comment]
All right, so we can close this?

**Comment by MinLL** [comment]
Yes
