### ISSUE TITLE
Unable to find quest item.

### ISSUE THREAD

**Issue by border999** [DeviousDevices/DDi#166]
for more than three IRL months, I have been unable to progress any farther in my quest to get the chastity belt removed because I have been unable to find the last item it requires me to find. It is not where it should be according to the "official" tutorial. It also does not appear on the map when I look for it. Any advice? Zed is no help even though he gave me the quest. I WANT THIS BELT OFF! I CAN'T DO ANYTHING WITHOUT HAVING AN ORGASM!! But I, want to keep the mod.

**Comment by TheKimy** [comment]
Known issue, but really needs fixing.

**Comment by TheKimy** [comment]
Yeah, quite likely. Let's just close this one.
