### ISSUE TITLE
Making Cuffs bindable? Ideas plox.

### ISSUE THREAD

**Issue by Coopervane** [DeviousDevices/DDi#51]
Soo, arm and leg cuffs then, they seem a bit wasted beeing just decorative items don't they? So let's toss out some ideas for how they could be made into temporarily bindable items.

The first thought that comes to my mind is to make them similar to the Armbinder, but not identical.

This includes them having 2 states: Worn, Worn+bound.

Cuffs will lock on as normal, you can wear them just as you can now as a decorative item, and a key is required to remove them. But they can also be locked togeather as a restraint, this can be done by the player via the inventory options, or it can be done by an NPC interaction similar to how Zen's gag-quest does the armbinder-tighten thing (this also lets mods like Helpless do some fun things with them).

When locked:

LegCuffs apply the "Slow-Move" and "No-Sprint" effects, but do not prevent inventory access or all the rest (you don't need legs for that).

ArmCuffs will apply a bound anim and work similar to the Armbinder (no sprint, no inventory, no fighting etc etc).

Getting out of them is the problem. I do not feel this should require a key, one is already needed to get the cuffs off, so i think we're looking at the Armbinder system again. Either struggle with them long enough, or ask a freindly NPC for help.

Ideas?

**Comment by Versh** [comment]
Uhm... I'm thinking about something a bit out of the line...
Why not a "magnetic trick" for event?
I know that is more a Sci-fi thing, but we talk about a world where there's the magic.. so: why not? or something similar

Something that force the player Hands in variable Offset by the Zaz offset
Like:
Hands back, release... Hands Yoke offset... Release... release... release... Slave posture offest (the hands that hold the forearms)... release

The offset of arms avoid the player to change the combat state (like a yoke) only if active, so It isn't very restrictive but only "possible" by the event probability setted by player

For the legs I was thinking about the Fnis Sexy Move: Force a walk type, but this will required a compatibility or an emulation, we should ask to Fore...

Is something like the Slave is commanded by an "ghost master"... eventually adding the possibility to try to resist.
