### ISSUE TITLE
Missing property in gagquest dialogue

### ISSUE THREAD

**Issue by Srende** [DeviousDevices/DDi#56]
[09/17/2014 - 08:03:47PM] Error: Cannot call PlayerRef() on a None object, aborting function call
stack:
	[topic info 1804B0C6 on quest zadGagQuest (1802B5EF)].zadGagTif15.Fragment_1() - "zadGagTif15.psc" Line 9
[09/17/2014 - 08:03:47PM] Error: Cannot call Moan() on a None object, aborting function call
stack:
	[topic info 1804B0C6 on quest zadGagQuest (1802B5EF)].zadGagTif15.Fragment_1() - "zadGagTif15.psc" Line 9

I've had this on two different saves so I'm reasonably sure it's actually an unset property instead of a problem on my end ^^

**Comment by MinLL** [comment]
Hmm. I've looked, and I don't see any problems here. Closing as "Cannot verify", until further verification.
