### ISSUE TITLE
Hood features

### ISSUE THREAD

**Issue by LLkoffii** [DeviousDevices/DDi#65]
Integrated blindfold (detachable, separately lockable)
integrated gag slot ( removable, separately lockable. should accept a variety of plugs - simple lid, inflatable, penis gag, deepthroat punishment gag, liquid dispenser gag)
and of course the hood itself should be lockable

Not sure whether the hood itself should act as a ring gag.

Ideas, particularly for different types of plugs, requested.

**Comment by Versh** [comment]
Hmm.. The unknown thing is a bit difficult, lots of quest refer to the player as the dragonborne, so It couldn't be done...
I think that is enough here... I mean: the hood isn't by itself a device.. but a semplified base for other devices...

Maybe a "free access" feature? An event that anyone feel free to add/remove plugs or Open/Close the blindfold zip...
In fact someone that go around with a Submission Hood is treated like a slave in a bondage club...

**Comment by LLkoffii** [comment]
http://www.loverslab.com/topic/41939-punishment-hood-mod-vision-other-ideas/
^ there's some pretty interesting ideas in this thread, might be worth a look.

**Comment by Aelie1** [comment]
Planning to use the 'merging' system we used in corsets to merge with gags, blindfolds, and collars.  Koffii will need to have multiple versions of the hood with each combination

**Comment by MinLL** [comment]
Hmmm. That's a lot of meshes / mesh combinations. I'm not sure if that's a good idea, unless we just use a "gag" and a "collar" model, without differentiating further.

**Comment by Aelie1** [comment]
Base
Base+Gag
Base+Collar
Base+Blindfold
Base+Gag+Blindfold
Base+Gag+Collar
Base+Blindfold+Collar
Base+Blindfold+Collar+Gag

It really depends on how long it would take koffii... i'll let him decide how many models to make

**Comment by MinLL** [comment]
Yeah, that's only if we use generic collar/gag models, no matter which is equipped. Otherwise, for every type of gag/collar, add more models exponentially.

Corset + Belt melding only permitting one type of belt is one thing (Not nearly as noticable as this, imo). 

I'm not convinced this is a good idea, given the work involved + the mediocre effect produced.

**Comment by Aelie1** [comment]
I thought koffii had shown off gag and blindfold attachments earlier

**Comment by TheKimy** [comment]
Well, one plug I'd really want to have is something like the panel gag plug, as in mostly flat, just with a visible lock in the middle or so. So you can just...shut them up and throw the key away! giggles

**Comment by LLkoffii** [comment]
Unfortunately it can't be a head-replacing mesh due to the blindfold - if you remove it, you want the eyes to be visible. I had planned on using the same setup as the harness gags used a while ago. That's changed in the mean time unfortunately.

**Comment by LLkoffii** [comment]
It would probably be ok to create just three or four nifs for the wearable items:
hood
blindfold
hood+gag
*or*
hood
hood+blindfold
hood+gag
hood+blindfold+gag

In the first case, adding extra plugs would just linearly increase the number of hood+gag meshes. And there would probably be only 2 or 3 in the first place - most plugs would just feature the same lock at the end.

Not sure why Aelie would suggest the collars should be merged too. In any case, merging collars would up the model count by 4 for each collar and I'm not sure that's something I'd be comfortable with. More importantly, the hood already features a sturdy-looking strap at the bottom for locking, so it should probably count as a collar itself. Especially since the hood by itself without the blindfold or plugs doesn't really do anything, much like a collar. It will likely also clip with the collars - since this is a head item, the tighter I make the hood, the more probability it will clip with someone's face. So we don't really want to make it too tight. But then some clipping with the collars is almost certain. It sucks, but there's just one bone there on the neck, and there isn't even a jaw bone to take deformations from. Skyrim's skeleton is pretty inadequate for what we're doing with it.

**Comment by Versh** [comment]
Sorry, I don't get it (and I'm ignorant about meshes, so this is basically to understand):
Why make 2 godzillion of meshes?

And not simply individual item + patch?

Like:
The Hood is One -> open in the eyes and in the mouth

Theres a mouth "patch device" (that isn't weareable individually) in 3 variant
*Closed (simply a string of rubber on the mouth that appear to be the same item, but it isn't)
*Gag Without plug
*Gag with plug
*None

The eyes is simply an opening cutted exactly as the current blindfold

The "patch" are memorized in the PapyrusUtil on the hood, so, when you equip it you get the hood THEN an auto add of a blindfold and the specific gag...

If you have already expained why it couldn't be done like that I'm sorry I'm not able to understand all of what you wrote...
