### ISSUE TITLE
Self-locking plugs Features

### ISSUE THREAD

**Issue by LLkoffii** [DeviousDevices/DDi#66]
These plugs should be lockable without a chastity belt. They also expand and contract.

Any ideas for other functionality?

**Comment by Versh** [comment]
Uhm.. Sorry, I dont get It: How it possible that stay in place without a belt?
Is something like Excalibur? :P

Sorry, poor joke.
I need some more information about it to give any suggestion

If I remember right they're a set of plugs oriented in a triangle, so they couldn't be removed, right?

In that case an "auto-defence" system: You get a lockpicking screen, if you break the lockpick they start to vibrate (that prevent any other escape try) with the standard lost of magicka/stamina, Shake camera, Player stumble (like heels)

**Comment by TheKimy** [comment]
We can go ahead and implement that, even without having dedicated models. Nobody can really see them anyway.

**Comment by TheKimy** [comment]
Princessity implemented that.
