### ISSUE TITLE
Coopervane's New Plug Effects

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#75]
Coopervane, on 18 Jan 2015 - 06:19 AM, said:

Min, on 17 Jan 2015 - 10:48 AM, said:
As a reminder, it is very easy for non-framework mods to create their own plug effects; Each is essentially just an enchantment on the item, often with a corresponding periodic event (See https://github.com/DeviousDevices/Docs/wiki/Periodic-Eventsfor details on periodic event creation).

Alright, that means i could use a little scripty help creating three new vibe-effects for DDx, all the stuff for this exists in DDi's code and as far as i can tell, and would just have to be Frankenstein'ed togeather. So i'm guessing this would be fairly easy for those who know scripting? Well hopefully..

Effect-1 : Very-strong vibe with shocking finish, always edges. The idea here is to periodically play the "very strong" vibe effect, but as soon as it finishes vibing a small painful shock is given. The strong vibe will add lots of arousal, the small shock will take some of it away so the player doesen't max out arousal too fast. When the player hits 100 arousal (edged), a strong shock is played (no vibe, just shock) that will send the arousal tumbling back down and the process starts over.

Effect 2 : Chaotic Vibe/shock effect, no edging. The idea here is to randomly choose one of a few effects to play when a vibe event is called, Normal-vibe / Strong-vibe / Verystrong-vibe / Shock. Thus the player never really knows what they are going to get. No edging here, this one can send the player climaxing IF they aren't unfortunate enough to get a shocker at 100 arousal instead of a vibe.

Effect 3 : Periodic shocking. Nothing fancy here, just replacing the periodic vibe effect with a small shock instead of a vibe. Similar to the current "ElectroStim" only it doesen't just happen at 100 arousal, it happens periodically and the shock should probably be weaker.

Any takers? Please? :blush:

I've updated the DDx Repo so that's current and can be worked on. It includes Aelies Kof-boot workaround so they can be worn with leg-cuffs, and it includes two stronger Soulgem plugs (Greater and Grand) which people are also very welcome to try out.

**Comment by MinLL** [comment]
I will implement this once the ESM is free.

**Comment by MinLL** [comment]
naaitsab, on 19 Jan 2015 - 08:51 AM, said:
As for the plug idea thing:
Have a plug that punishes the player (stamina, health and magicka) when the player isn't applying the vibrate spell on herself with a x hour interval (PC hears x pings notification). The plugs are edge only of course ;)
Also the plugs should come with a vibrate spell when applied. maybe a new variant that has a random vibration strength to it instead of the ones now which have a set value depending on the spell. The magicka required should be so that even a warrior can trigger it.

**Comment by Versh** [comment]
I'll give a look...
