### ISSUE TITLE
Armbinder slot fix

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#76]
Move armbinders to slot 39 to allow gloves to be worn underneath.  I've updated the meshes in DDa to use slot 39 and updated the vanilla armbinders to occupy slot 39 and also hide 33(hands) and 59(armcuffs)

this will require custom armbinders to be updated in order for them to show up. 

(easy fix though)
just change your custom armbinder to use slot 39, and if you have a custom 'armor addon' have it use slots 33, 39, and 59

**Comment by MinLL** [comment]
Note to self: Don't close this before fixing hardcoded slot references.

**Comment by Coopervane** [comment]
DDx has it sorted.
