### ISSUE TITLE
Restrictive Corset Gameplay Features

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#79]
Add koffii's corset as a new item with special effects.

koffii has created a number of meshes for the corset:
-corset
-corset with chastity belt
-corset with open chastity belt

This corset normally uses the slot 58(harnesses).  when the player wears a belt at the same time, it has the special effect of hiding that belt and replacing itself with a 'chastity corset' or 'chastity corset(open).

when the player uses a chastity key to remove the belt, it changes back to the normal corset.

there are two methods for dealing with removing the corset:

1)
if the player removes the corset while it is combined, the corset is removed and the belt comes back from being hidden.  the main problem with this is that the belt reappears "by magic".

2)
block the player from removing the corset while it is attached to a belt.  this avoids the 'magic reappearing belt' but it makes the two items less independent.

For this issue min will handle the creation of the script that handles the combination and removal and aelie will handle the CK edits

**Comment by Aelie1** [comment]
basic ck stuff is in the esm now, more stuff will be done when the combining script is done

**Comment by MinLL** [comment]
Automerge script is done.

**Comment by MinLL** [comment]
Stamina Penalty
Shout Stagger or Shout Cooldown Penalty

**Comment by Aelie1** [comment]
stamina penalty done
