### ISSUE TITLE
Yoke Dialogue

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#87]

**Comment by zenetx** [comment]
Should yoke gagged dialogues belong to this ticket too? 

I would gladly help to include those in the merged gagged system.

**Comment by MinLL** [comment]
Yup, yoke gagged dialogues will need to be included as well.

**Comment by Aelie1** [comment]
done in 984c12a

**Comment by MinLL** [comment]
Is gagged yoke dialogue implemented? If so, reclose this.

**Comment by Aelie1** [comment]
As far as I know zenetx was going to handle that
