### ISSUE TITLE
koffii's gear missing textures

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#90]
koffii's gear had its textures removed, someone needs to put them back.  (maybe this is just a git operation?)

**Comment by Coopervane** [comment]
I've got'em, just tell me when.

**Comment by Aelie1** [comment]
i uploaded the ones i had from nov 27, if these are not the latest versions feel free to upload yours on top

**Comment by Coopervane** [comment]
There were some changes to the textures around that time, i'm not sure if that was before or after the 27'th though..

**Comment by Aelie1** [comment]
feel free to use the ones you know are correct then

**Comment by Coopervane** [comment]
Just had a peek, and they seem to be the current ones.

I suspect you can close this then :)
