### ISSUE TITLE
Keywords + Properties

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#94]
zadLibs
Keyword Property zad_DeviousYoke Auto
Keyword Property zad_DeviousCorset Auto
Keyword Property zad_DeviousClamps Auto
Keyword Property zad_DeviousGloves Auto
Keyword Property zad_DeviousHood Auto
Keyword Property zad_DeviousSuit Auto
zadYokeQuestScript Property ybq Auto

zadBQ00:
zadYokeQuestScript Property ybq Auto

**Comment by Aelie1** [comment]
i left these undone:

zadLibs
zadYokeQuestScript Property ybq Auto

zadBQ00:
zadYokeQuestScript Property ybq Auto

**Comment by MinLL** [comment]
This is done.
