### ISSUE TITLE
move vaginal piercings away from their current slot

### ISSUE THREAD

**Issue by Aelie1** [DeviousDevices/DDi#95]
2 options:

1) changing it to an art object (this requires modelling work which is not desirable right now)

2) using the 'model hider' as a surrogate model, the vaginal piercing rendered will change the model hider's mesh to the vaginal piercing (and change it back when it is removed)

**Comment by MinLL** [comment]
Resolved by 2194133731ebb454c086df55ad465ed73a0e2254 and 9bfa65297f446b3b75ab1961fbbfb25dfc2c77cf.
